spring.application.name=nation-news-backend

# ==========================
# DATABASE
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# SERVER
# ==========================
server.port=${PORT:8080}

# ==========================
# LOGGING
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.context.config=DEBUG

# ==========================
# FILE UPLOAD
# ==========================
file.upload-dir=uploads